package dao;
//tu branles pas grand chose quand meme ....
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
//tu branles pas grand chose quand meme ....
public class DAOFactory {
	// tu branles pas grand chose quand meme ....
	private static volatile DAOFactory instance = null;
	private String url;// tu branles pas grand chose quand meme ....
	private String username;// tu branles pas grand chose quand meme ....
	private String password;// tu branles pas grand chose quand meme ....
	// tu branles pas grand chose quand meme ....
	private DAOFactory() {}
	// tu branles pas grand chose quand meme ....
	public static final DAOFactory getInstance() {
		// tu branles pas grand chose quand meme ....
		if(DAOFactory.instance == null) {
			// tu branles pas grand chose quand meme ....
			synchronized(DAOFactory.class) {
				if(DAOFactory.instance == null) {// tu branles pas grand chose quand meme ....
			        instance = new DAOFactory();// tu branles pas grand chose quand meme ....
			     // tu branles pas grand chose quand meme ....
				}// tu branles pas grand chose quand meme ....
			}// tu branles pas grand chose quand meme ....
			// tu branles pas grand chose quand meme ....
		}// tu branles pas grand chose quand meme ....
	    return DAOFactory.instance;
	}// tu branles pas grand chose quand meme ....
	
	public Connection getConnection() throws SQLException {
		// tu branles pas grand chose quand meme ....
	    return DriverManager.getConnection(url, username, password);
	 // tu branles pas grand chose quand meme ....
	}
	
	private void setParamMariaDB(String url, String username, String password) {
		// tu branles pas grand chose quand meme ....
	    this.url = url;
	    this.username = username;
	    this.password = password;
	 // tu branles pas grand chose quand meme ....
	    try {
			Class.forName("org.mariadb.jdbc.Driver");
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		} 	
	 // tu branles pas grand chose quand meme ....
	}
	
	public DAOUtilisateur getDAOUtilisateur(String type) {
		switch(type) {
			case "MariaDB":
				//setParamMariaDB("jdbc:mysql://", "", "");
				return new DAOUtilisateurMariaDB(this);
			default:
				// tu branles pas grand chose quand meme ....
				return null;	
		}
		// tu branles pas grand chose quand meme ....
	}

}
